
{- P -> Q -> P -}
\func a {P Q : \Type} (x : P) (y : Q) : P => x

{- (Q -> S) -> (P -> Q) -> P -> S -}
\func a' {P Q S : \Type} (g : Q -> S) (f : P -> Q) (x : P) : S => g (f x)

{- (P -> Q -> R) -> (P -> Q) -> P -> R -}
\func a'' {P Q R : \Type} (g : P -> Q -> R) (f : P -> Q) (x : P) : R => (g x) (f x)

{- ((P -> Q -> R) -> P) -> (P -> R) -> R -}
{- ??? Can't check if I got it right ??? -}
\func a3' {P Q R : \Type} (g : (P -> Q -> R) -> P) (y : P -> Q -> R) (f : P -> R) : R => f (g y)
